spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/ms-loan
  cloud:
    discovery:
      enabled: true
  application:
    name: gateway-service
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
